twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        ga_code: 'gAXXXDDDDDDDDDD'
    form_themes: ['bootstrap_5_layout.html.twig']
when@test:
    twig:
        strict_variables: true
        debug: true



